### ISSUE TITLE
Color in tree_map using D3PlusR function

### ISSUE THREAD

**Issue by paeselhz** [paulofelipe/D3plusR#1]
I'm running an algorithm to create multiple hierarchic treemaps, but, the color scheme only appears at one level, and I was wondering if there is any way to make all the levels of hierarchy to have color.

Thanks in advance.
Luis Paese

**Comment by paulofelipe** [comment]
Hi, @paeselhz 

Could you please give an example of the code that you are using?

Thanks!

**Comment by paeselhz** [comment]
Hi @paulofelipe , below is a copy of my code:

setwd("/home/lhzpaese/Documents/Matriculas_para_app/")

library(readr)
library(D3plusR)
library(dplyr)
  
Matricula_total <- readRDS("Matricula_RS_completa.rds")

aux <- Matricula_total %>%
      filter(Ano == 2016)

d3plus(data = aux,
       type = "tree_map",
       id = c("Cidade", "NO_ENTIDADE", "Grupo", "Etapa"),
       width = "100%",
       height = 300) %>%
  d3plusSize(value = "N") %>%
  d3plusLegend(value = TRUE, order = list(sort = "desc", value = "size")) %>%
  d3plusColor("NO_ENTIDADE") %>%
  d3plusDepth(0) %>%
  d3plusLabels(valign = "top")

If you wish, I can send you a copy of the file I'm using.

Thanks!

**Comment by paulofelipe** [comment]
@paeselhz , have you tried delete the `d3plusColor()` line?

If you pass one value, the color is fixed to this value. If you don't use this function, the D3plus will automatically set the colors. 

Let me know if you don't get the expected behavior.

Thanks.

**Comment by paeselhz** [comment]
Thank you for your answer! It worked perfectly fine!!!

Thanks!
Luis Paese
