### ISSUE TITLE
Doubts regarding Color and Font attributes

### ISSUE THREAD

**Issue by paeselhz** [paulofelipe/D3plusR#2]
I'm developing a shiny web-app using the treemap feature from D3plus, and I was wondering how could I set the color scheme through hierachy levels, and also how could I change the font to a google fonts font.

Thanks in advance,
Luis paese

**Comment by paulofelipe** [comment]
Hi, Luis! 

Could you check if the example below solves your problem?

```r
library(D3plusR)
library(magrittr)

data <- data.frame(level1 = c('a', 'a', 'b', 'b'),
                   level2 = c('x', 'y', 'z', 'w'),
                   value = c(10, 20, 15, 5))

attributes <- list(level1 = data.frame(level1 = c('a', 'b'),
                                       color = c("#AD1818", "#5F4BC2")),
                   level2 = data.frame(level2 = c('x', 'y', 'z', 'w'),
                                       color = c("#3AC4BB", "#AD802D", 
                                                 "#105219", "#B7DB25")))

d3plus(data = data,
       type = "tree_map",
       id = c('level1', 'level2'),
       width = "100%") %>% 
  d3plusSize("value") %>% 
  d3plusAttrs(attributes) %>% 
  d3plusTitle("Acesso aos Dados") %>% 
  d3plusColor("color") %>% 
  d3plusFont(family = "Indie Flower")
```

You have to add `<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">` in your application. You could use `tags$head()`.

Let me know if you have any problem.

**Comment by paeselhz** [comment]
Thanks! Everything worked perfectly!

**Comment by paeselhz** [comment]
Just another question... If I want to change the text displayed in tooltips, how could that be done? For example, in plotly I set a text attribute, and write in HTML what I wish to display. Is there anyway this could be done with d3plus?

Thanks again!

**Comment by paulofelipe** [comment]
I don't know if I got it right, but you can use the dictionary option to change texts. You can also include html code directly in the tooltip.
```r
library(D3plusR)
library(magrittr)

data <- data.frame(level1 = c('a', 'a', 'b', 'b'),
                   level2 = c('x', 'y', 'z', 'w'),
                   value = c(10, 20, 15, 5))

attributes <- list(level1 = data.frame(level1 = c('a', 'b'),
                                       color = c("#AD1818", "#5F4BC2")),
                   level2 = data.frame(level2 = c('x', 'y', 'z', 'w'),
                                       color = c("#3AC4BB", "#AD802D", 
                                                 "#105219", "#B7DB25")))

dictionary <- list(a = "Sector A", b = "Sector B",
                   x = "Product Y", y = "Product Y",
                   z = "Product Z", w = "Product W")

d3plus(data = data,
       type = "tree_map",
       id = c('level1', 'level2'),
       dictionary = dictionary,
       width = "100%") %>% 
  d3plusSize("value") %>% 
  d3plusAttrs(attributes) %>% 
  d3plusTitle("Acesso aos Dados") %>% 
  d3plusColor("color") %>% 
  d3plusFont(family = "Indie Flower") %>% 
  d3plusTooltip(html = "<h1>Test!</h1>")
```

**Comment by paeselhz** [comment]
I'm sorry to reopen this issue, but I've tried to use the code you pasted above, and the Tooltop feature doesn't seem to be working for me.

Edit: The tooltip is modifyable, but only using values of my dataset, I cannot declare a HTML statement to be displayed inside the Tooltip like the example before.

**Comment by paeselhz** [comment]
I'm sorry to reopen this issue, but I've tried to use the code you pasted above, and the Tooltop feature doesn't seem to be working for me.

**Comment by paulofelipe** [comment]
When you try to put some html code in 'd3plusTooltip()` do you receive an error message?

**Comment by yenhsieh** [comment]
Hi and thank for the helpful package.

Just to follow this issue regarding the part of tooltip function since I'd like to use customized tooltip for each treemap component(e.g. `<a href="http://examplelink.net/search/y">y</a>` while x comes from the data$level2[2] in your example data).

Is it possible to take variable instead of text string in html tag?
like `d3plusTooltip(html =  paste0("<a href='http://examplelink.net/search/", variable, "'>", variable, "</a>")`

Thanks :)

**Comment by paulofelipe** [comment]
Hi @yenhsieh , 

Probably there is a best answer, but this code do what you want (I think). You will need use a little bit of javascript code:

```r
library(D3plusR)
library(magrittr)
library(htmlwidgets)

data <- data.frame(level1 = c('a', 'a', 'b', 'b'),
                   level2 = c('x', 'y', 'z', 'w'),
                   value = c(10, 20, 15, 5))

attributes <- list(level1 = data.frame(level1 = c('a', 'b'),
                                       color = c("#AD1818", "#5F4BC2")),
                   level2 = data.frame(level2 = c('x', 'y', 'z', 'w'),
                                       color = c("#3AC4BB", "#AD802D", 
                                                 "#105219", "#B7DB25")))

dictionary <- list(a = "Sector A", b = "Sector B",
                   x = "Product X", y = "Product Y",
                   z = "Product Z", w = "Product W")


d3plus(data = data,
       type = "tree_map",
       id = c('level1', 'level2'),
       dictionary = dictionary,
       width = "100%") %>% 
  d3plusSize("value") %>% 
  d3plusAttrs(attributes) %>% 
  d3plusTitle("Acesso aos Dados") %>% 
  d3plusColor("color") %>% 
  d3plusFont(family = "Indie Flower") %>% 
  onRender('function(el, x, data){
             var viz = this.viz;
             viz.tooltip({
      	      "html": function(d) {
      	        return "<h1>" + d + "</h1>";
              }
            })
  }')

```

**Comment by yenhsieh** [comment]
Hi @paulofelipe

Really appreciate your great help and it works for a total JS stranger like me. 

Thanks again
