### ISSUE TITLE
Wrapper functions for using D3plusR in shiny

### ISSUE THREAD

**Issue by faustocarva** [paulofelipe/D3plusR#3]
Hi Paulo, would it be nice to have D3plusR outputs in Shiny apps. We need a wrapper function that uses htmlwidgets to plot content in Shiny. This issue works like a reminder for a future implementation.

**Comment by renanxcortes** [comment]
@faustocarva this is a great idea. Actually, it's already possible to do this by wrapping it with renderUI. If you want a example, take a look at some of the apps in my 'VisualizaFEE' repo in my account (sorry, I'm typing with my cellphone, so I can't paste a reproducible here).

**Comment by paulofelipe** [comment]
Hi @faustocarva , as @renanxcortes said this functionality is already implemented. You can take a look at the renan repo and/or see the example in this link: https://paulofelipe.github.io/tutorial_d3plusr/shiny.html#shiny (tutorial in portuguese).

Regards,

Paulo

**Comment by faustocarva** [comment]
Thanks.
